"""
Django settings for hotel_project project.

Generated by 'django-admin startproject' using Django X.Y.Z.

For more information on this file, see
https://docs.djangoproject.com/en/X.Y/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/X.Y/ref/settings/
"""

from pathlib import Path
import os
import sys # Importar sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Añadir el directorio 'apps' al sys.path para que Django pueda encontrar las aplicaciones
# Esto es útil si has estructurado tus apps dentro de un subdirectorio 'apps/'
# Asumiendo que BASE_DIR es hotel_project/hotel_project/, entonces BASE_DIR.parent es hotel_project/
sys.path.insert(0, os.path.join(BASE_DIR.parent, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/X.Y/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aqui-va-tu-clave-secreta-generada-por-django' # Cambia esto en producción

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Cambia esto a False en producción

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps', # Para sitemaps

    # Mis aplicaciones (asegúrate que los nombres coincidan con apps.py de cada app)
    # Si usaste 'python manage.py startapp <nombre_app> apps/<nombre_app>',
    # el nombre de la app para INSTALLED_APPS es solo '<nombre_app>'
    # Django buscará en el sys.path que modificamos.
    'core', #.apps.CoreConfig',
    'habitaciones', #.apps.HabitacionesConfig',
    'reservas', #.apps.ReservasConfig',
    'clientes', #.apps.ClientesConfig',
    'servicios', #.apps.ServiciosConfig',

    # Aplicaciones de terceros (si las usas, ej. crispy_forms, etc.)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Para internacionalización
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hotel_project.urls' # Este es hotel_project/hotel_project/urls.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # BASE_DIR.parent apunta al directorio raíz del proyecto (donde está manage.py)
        'DIRS': [os.path.join(BASE_DIR.parent, 'templates')], # Directorio de templates globales
        'APP_DIRS': True, # Django buscará templates dentro de las carpetas 'templates' de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_project.wsgi.application' # Este es hotel_project/hotel_project/wsgi.py


# Database
# https://docs.djangoproject.com/en/X.Y/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent / 'db.sqlite3', # La BD estará en la raíz del proyecto
    }
}
# Para PostgreSQL en producción (ejemplo):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'nombre_db_hotel',
#         'USER': 'usuario_db_hotel',
#         'PASSWORD': 'password_db_hotel',
#         'HOST': 'localhost', # o la dirección del servidor de BD
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/X.Y/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization (i18n) and Localization (L10n)
# https://docs.djangoproject.com/en/X.Y/topics/i18n/

LANGUAGE_CODE = 'es' # Idioma principal: Español

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'), # Ejemplo si quieres soportar inglés también
    # Añade más idiomas según necesites
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR.parent, 'locale'), # Directorio para archivos de traducción, en la raíz del proyecto
]

TIME_ZONE = 'UTC' # Ajusta a tu zona horaria, ej: 'America/Mexico_City'

USE_I18N = True

USE_L10N = True # Para formatos de fecha, número, etc. localizados

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/X.Y/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # Directorio para archivos estáticos globales del proyecto, en la raíz del proyecto
    os.path.join(BASE_DIR.parent, 'static'),
]
# STATIC_ROOT = os.path.join(BASE_DIR.parent, 'staticfiles_production') # Para 'collectstatic' en producción

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/X.Y/topics/files/

MEDIA_URL = '/media/'
# Directorio donde se guardarán los archivos subidos por usuarios, en la raíz del proyecto
MEDIA_ROOT = os.path.join(BASE_DIR.parent, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/X.Y/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF_COOKIE_SECURE = True # Descomentar en producción (HTTPS)
# SESSION_COOKIE_SECURE = True # Descomentar en producción (HTTPS)
# SECURE_SSL_REDIRECT = True # Descomentar en producción (HTTPS)
# SECURE_HSTS_SECONDS = 31536000 # Descomentar en producción (HTTPS)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Descomentar en producción (HTTPS)
# SECURE_HSTS_PRELOAD = True # Descomentar en producción (HTTPS)

# Email backend (para desarrollo, imprime emails a la consola)
# En producción, configurar un backend SMTP real (ej. SendGrid, Mailgun, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu_email@example.com'
# EMAIL_HOST_PASSWORD = 'tu_password'
# DEFAULT_FROM_EMAIL = 'webmaster@example.com'

# LOGIN_URL = 'login' # Si tienes un sistema de login personalizado
# LOGOUT_REDIRECT_URL = 'inicio' # Página a la que redirigir después del logout
# LOGIN_REDIRECT_URL = 'inicio' # Página a la que redirigir después del login
